name: CI/CD pipeline to deploy to k8s

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Maven Validate
      - name: Validate with Maven
        run: mvn validate

      # Maven Compile
      - name: Compile with Maven
        run: mvn compile

      # Maven Test
      - name: Test with Maven
        run: mvn test

      # Maven Package
      - name: Package with Maven
        run: mvn clean package

      # Verify WAR file
      - name: Verify WAR file
        run: ls -lh target/

      # SonarQube Scan
      - name: SonarQube Scan
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=train-ticket-reservation \
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
